#!/usr/bin/env bash
#
# Regenerate /etc/samba/timenest-shares.conf with one explicit `include`
# per /etc/timenest/shares.d/*.conf fragment.
#
# Samba does not expand wildcards in `include =`, so a literal
# `include = /etc/timenest/shares.d/*.conf` silently loads nothing and every
# client gets NT_STATUS_BAD_NETWORK_NAME. Called by the entrypoint and by
# create-user.sh / delete-user.sh before reloading smbd.

set -euo pipefail

SHARES_DIR=/etc/timenest/shares.d
OUT=/etc/samba/timenest-shares.conf

mkdir -p "$SHARES_DIR" /etc/samba
TMP=$(mktemp /etc/samba/.timenest-shares.XXXXXX)

shopt -s nullglob
{
    echo "# Generated by sync-shares.sh - do not edit"
    for conf in "$SHARES_DIR"/*.conf; do
        printf 'include = %s\n' "$conf"
        printf '[sync-shares] loading share config: %s\n' "$conf" >&2
    done
} > "$TMP"

chmod 0644 "$TMP"
mv -f "$TMP" "$OUT"
